/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module alu(a, b, sel, result);
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  input sel;
  wire sel;
  output [1:0] result;
  wire [1:0] result;
  wire _0_;
  wire _1_;
  wire _2_;
  XOR2X1 _3_ (
    .A(a[0]),
    .B(b[0]),
    .Y(result[0])
  );
  OAI21X1 _4_ (
    .A(a[0]),
    .B(sel),
    .C(b[0]),
    .Y(_2_)
  );
  AOI21X1 _5_ (
    .A(a[0]),
    .B(sel),
    .C(_2_),
    .Y(_0_)
  );
  XNOR2X1 _6_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_1_)
  );
  XNOR2X1 _7_ (
    .A(_0_),
    .B(_1_),
    .Y(result[1])
  );
endmodule

module counter(clk, rst, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  INVX1 _11_ (
    .A(count[3]),
    .Y(_04_)
  );
  INVX1 _12_ (
    .A(rst),
    .Y(_05_)
  );
  AND2X1 _13_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_06_)
  );
  NAND3X1 _14_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_07_)
  );
  OAI21X1 _15_ (
    .A(count[2]),
    .B(_06_),
    .C(_05_),
    .Y(_08_)
  );
  AOI21X1 _16_ (
    .A(count[2]),
    .B(_06_),
    .C(_08_),
    .Y(_00_)
  );
  OAI21X1 _17_ (
    .A(count[1]),
    .B(count[0]),
    .C(_05_),
    .Y(_09_)
  );
  NOR2X1 _18_ (
    .A(_06_),
    .B(_09_),
    .Y(_01_)
  );
  NOR2X1 _19_ (
    .A(count[0]),
    .B(rst),
    .Y(_02_)
  );
  OAI21X1 _20_ (
    .A(_04_),
    .B(_07_),
    .C(_05_),
    .Y(_10_)
  );
  AOI21X1 _21_ (
    .A(_04_),
    .B(_07_),
    .C(_10_),
    .Y(_03_)
  );
  DFFPOSX1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  DFFPOSX1 _23_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  DFFPOSX1 _24_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[2])
  );
  DFFPOSX1 _25_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule

module mini_soc(clk, rst, alu_sel, mux_sel, soc_out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input alu_sel;
  wire alu_sel;
  input mux_sel;
  wire mux_sel;
  output [1:0] soc_out;
  wire [1:0] soc_out;
  wire [1:0] alu_out;
  wire [3:0] count;
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel(alu_sel)
  );
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  mux2x1 u_mux (
    .in0(count[3:2]),
    .in1(alu_out),
    .out(soc_out),
    .sel(mux_sel)
  );
endmodule

module mux2x1(in0, in1, sel, out);
  input [1:0] in0;
  wire [1:0] in0;
  input [1:0] in1;
  wire [1:0] in1;
  input sel;
  wire sel;
  output [1:0] out;
  wire [1:0] out;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  INVX1 _4_ (
    .A(in0[0]),
    .Y(_2_)
  );
  INVX1 _5_ (
    .A(in0[1]),
    .Y(_3_)
  );
  NAND2X1 _6_ (
    .A(in1[0]),
    .B(sel),
    .Y(_0_)
  );
  OAI21X1 _7_ (
    .A(_2_),
    .B(sel),
    .C(_0_),
    .Y(out[0])
  );
  NAND2X1 _8_ (
    .A(sel),
    .B(in1[1]),
    .Y(_1_)
  );
  OAI21X1 _9_ (
    .A(sel),
    .B(_3_),
    .C(_1_),
    .Y(out[1])
  );
endmodule
